# Generated by Django 5.0.6 on 2024-10-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_alter_comment_blog_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
